# Generated by Django 3.2.14 on 2025-04-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250331_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='saledata',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saledata',
            name='order',
        ),
        migrations.RemoveField(
            model_name='item',
            name='aisle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='case_quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='case_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Aisle',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderShipment',
        ),
        migrations.DeleteModel(
            name='SaleData',
        ),
    ]
